-- PROJETO DE CONTROLE DE SISTEMA ACADÊMICOS

CREATE DATABASE FACULDADE; -- CRIAÇÃO DO BANCO

USE FACULDADE; -- UTILIZAÇÃO DO BANCO

-- CRIAÇÃO DAS TABELAS

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(100),
	ID_ENDERECO INT
);

CREATE TABLE ENDERECO_ALUNO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(80),
	CIDADE VARCHAR(80),
	BAIRRO VARCHAR(80),
	UF CHAR(2),
	CEP VARCHAR(10)
);

CREATE TABLE PROFESSOR(
	IDPROFESSOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(100),
	ID_DISCIPLINA INT
);

CREATE TABLE DISCIPLINA(
	IDDISCIPLINA INT PRIMARY KEY AUTO_INCREMENT,
	DISCIPLINA VARCHAR(100) NOT NULL UNIQUE,
	DURACAO_DISCIPLINA CHAR(2),
	ID_CURSO INT
);

CREATE TABLE CURSO(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	CURSO VARCHAR(100) NOT NULL UNIQUE,
	DURACAO_CURSO CHAR(4)
);

CREATE TABLE TURMA(
	IDTURMA INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(100)
);

CREATE TABLE ALUNO_DISCIPLINA(
	ID_ALUNO INT,
	ID_DISCIPLINA INT,
	PRIMARY KEY(ID_ALUNO, ID_DISCIPLINA)
);

CREATE TABLE PROFESSOR_TURMA(
	ID_PROFESSOR INT,
	ID_TURMA INT,
	PRIMARY KEY(ID_PROFESSOR, ID_TURMA)
);

CREATE TABLE TURMA_DISCIPLINA(
	ID_TURMA INT,
	ID_DISCIPLINA INT,
	PRIMARY KEY(ID_TURMA, ID_DISCIPLINA)
);

-- ALTERANDO TABELAS PARA INSERÇÃO DE FOREIGN KEYS PARA QUE ESSAS SEJAM CONSTRAINTS NOMEADAS

ALTER TABLE ALUNO
ADD CONSTRAINT FK_ALUNO_TELEFONE
FOREIGN KEY(ID_ENDERECO)
REFERENCES ENDERECO_ALUNO(IDENDERECO);

ALTER TABLE PROFESSOR
ADD CONSTRAINT FK_PROFESSOR_DISCIPLINA
FOREIGN KEY(ID_DISCIPLINA)
REFERENCES DISCIPLINA(IDDISCIPLINA);

ALTER TABLE DISCIPLINA
ADD CONSTRAINT FK_DISCIPLINA_CURSO
FOREIGN KEY(ID_CURSO)
REFERENCES CURSO(IDCURSO);

ALTER TABLE ALUNO_DISCIPLINA
ADD COSTRAINT FK_ALUNO
FOREIGN KEY(ID_ALUNO)
REFERENCES ALUNO(IDALUNO);

ALTER TABLE ALUNO_DISCIPLINA
ADD COSTRAINT FK_DISCIPLINA
FOREIGN KEY(ID_DISCIPLINA)
REFERENCES DISCIPLINA(IDDISCIPLINA);

ALTER TABLE PROFESSOR_TURMA
ADD COSTRAINT FK_PROFESSOR
FOREIGN KEY(ID_PROFESSOR)
REFERENCES PROFESSOR(IDPROFESSOR);

ALTER TABLE PROFESSOR_TURMA
ADD COSTRAINT FK_TURMA	
FOREIGN KEY(ID_TURMA)
REFERENCES TURMA(IDTURMA);

ALTER TABLE TURMA_DISCIPLINA
ADD CONSTRAINT FK TURMA
FOREIGN KEY(ID_TURMA)
REFERENCES TURMA(IDTURMA);

ALTER TABLE TURMA_DISCIPLINA
ADD CONSTRAINT FK DISCIPLINA
FOREIGN KEY(ID_DISCIPLINA)
REFERENCES DISCIPLINA(IDDISCIPLINA);

-- CRIAÇÃO DE PROCEDURES PARA CADASTRO DE ALUNOS, TENDO ENTÃO A REGRA DE NEGÓCIO NO BANCO E NÃO NA APLICAÇÃO

-- INSERTS 

-- CRIAÇÃO DE VIEWS PARA EXTRAÇÃO DE RELATÓRIOS

-- TRIGGERS

-- QUERYS

































